# Пути ботов/сканеров уязвимостей — совпадение с любым regex здесь сразу
# отдаёт 404 в RoutesLost (app/controllers/routes_lost.rb), без записи в
# lost-url лог (иначе он тонет в этом шуме) и без похода в БД. Файл в
# lib/, не модель в БД — эти правки делает разработчик через код, а не
# через админку, и список должен разъезжаться по всем проектам вместе с
# остальным общим кодом через git, а не жить отдельно в БД каждого проекта.
BLOCKED_PATHS = [
  /\/mini$/,
  /\.php/,
  /\/wp-includes\//,
  /\/assets\//,
  /phpinfo/,
  /php_info/,
  /\.env\z/,
  /\.tar/,
  /\.rar/,
  /\.gz/,
  /\.env/,
  /\.aws\z/,
  /php-/,
  /\.git/,
  /\.svn\z/,
  /\.json\z/,
  /\.wp-/,
  /cgi-bin/,
  # /cms/,
  /\/log\//,
  /\.log/,
  /\/go\//,
  /\.cgi\z/,
  /\.tar.gz\z/,
  /\.yaml\z/,
  /\.zip\z/,
  /\.yml\z/,
  /\.py\z/,
  /\.sql\z/,
  /\/wp\//,
  /\.well-known/,
  /\.save/,
  /\.remote/,
  /\.local/,
  /\.production/,
  /\/gists\//,
  /\.ini/,
  /.+\/\z/,

  /\/_next\/data/,
  /\/\.htpasswd/,
  /\/\.htaccess/,
  /\/api\/action/,
  /\/api\/actions/,
  /\/apps/,
  /\/lib\.js/,
  /\/api\.js/,
  /\/connection\.js/,
  /\/auth\.js/,
  /\/security\.js/,
  /\/env/,
  /\/webpack\.config\.js/,
  /\/index\.js/,
  /\/cdn\.js/,
  /\/wp-json/,
  /\/license\.txt/,
  /\/main\.js/,
  /\/config\.js/,
  /\/browser\.html/,
  /\/_next/,
  /\/sign-up$/,
  /\/index\.jsp/,
  /\/login\.html/,
  /\/showLogin\.cc/,
  /\/login\.do/,
  /\/Web\/Auth/,
  /\/AppsLocalLogin\.jsp/,
  /\/SiteLoader/,
  /\/mPlayer/,
  /\/file\.ext/,
  /\/containers\/json/,
  /\/wp-config/,
  /\/xyz\z/,
  /\/ads.txt\z/,
  /\/aws.config.js\z/,
  /\/invoke.js\z/,
  /_profiler/,
  /\/database.js\z/,
  /\.htm\z/,
  /\.html\z/,
  /\.ashx\z/,

  /\/wp-login\z/,
  /\/login\z/,
  /\/api-docs\z/,
].freeze
